name: Unity Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Unity
        uses: game-ci/unity-setup@v2
        with:
          unityVersion: '2022.3.37f1' # 사용 중인 Unity 버전

      - name: Request activation (manual)
        uses: game-ci/unity-request-manual-activation-file@v2
        with:
          unitySerial: ${{ secrets.UNITY_SERIAL }}
    
      - name: Build WebGL
        run: |
          /opt/unity/Editor/Unity -batchmode -nographics -quit -projectPath . -buildTarget WebGL -executeMethod BuildScript.BuildWebGL
